### ISSUE TITLE
Unable to complete the setup using docker-compose.yaml file.

### ISSUE THREAD

**Issue by surenganne** [alonsomedo/os-data-stack#2]
I have stopped the build multiple times to check if these containers are created, I see the problem with the below three services. Can you guide me with the installation please?

Looks like it's never ending process:

[+] Running 0/3
 ⠹ Container airbyte-server  Creating                                                                                 896.2s
 ⠹ Container airbyte-worker  Creating                                                                                 896.2s
 ⠹ Container airbyte-cron    Creating                                                                                 896.2s

Also, I see the below warnings:

WARN[0000] The "CDK_VERSION" variable is not set. Defaulting to a blank string.
WARN[0000] The "PYTHON_VERSION" variable is not set. Defaulting to a blank string.
WARN[0000] The "DEPLOYMENT_MODE" variable is not set. Defaulting to a blank string.
WARN[0000] The "LOG_CONNECTOR_MESSAGES" variable is not set. Defaulting to a blank string.
WARN[0000] The "SECRET_PERSISTENCE" variable is not set. Defaulting to a blank string.
WARN[0000] The "JOB_ERROR_REPORTING_SENTRY_DSN" variable is not set. Defaulting to a blank string.
WARN[0000] The "APPLY_FIELD_SELECTION" variable is not set. Defaulting to a blank string.
WARN[0000] The "FIELD_SELECTION_WORKSPACES" variable is not set. Defaulting to a blank string.
WARN[0000] The "NEW_SCHEDULER" variable is not set. Defaulting to a blank string.
WARN[0000] The "SECRET_PERSISTENCE" variable is not set. Defaulting to a blank string.
WARN[0000] The "JOB_ERROR_REPORTING_SENTRY_DSN" variable is not set. Defaulting to a blank string.
WARN[0000] The "WORKER_ENVIRONMENT" variable is not set. Defaulting to a blank string.
WARN[0000] The "GITHUB_STORE_BRANCH" variable is not set. Defaulting to a blank string.
WARN[0000] The "DEPLOYMENT_MODE" variable is not set. Defaulting to a blank string.
WARN[0000] The "REMOTE_CONNECTOR_CATALOG_URL" variable is not set. Defaulting to a blank string.
WARN[0000] The "TEMPORAL_HISTORY_RETENTION_IN_DAYS" variable is not set. Defaulting to a blank string.
WARN[0000] The "UPDATE_DEFINITIONS_CRON_ENABLED" variable is not set. Defaulting to a blank string.

**Comment by alonsomedo** [comment]
Hello @surenganne ,

The initialization of the containers takes a while, please wait. Or try running docker-compose --build again. 

Let me know if that works, please.

**Comment by surenganne** [comment]
Does it take more than an hour?

**Comment by alonsomedo** [comment]
ohh no, definitely not. Do you have enough ram? recommended is 8-10gb

**Comment by surenganne** [comment]
Let me help you understand in detail. I have created a instance on AWS with 16Gb RAM and tried and also tried to install the same on my MacOS which is M2 with 16Gb. I am facing the same issue while building.

I am now posting the logs from MacOS server.

[+] Running 0/4
 ⠋ Container os-data-stack-postgres_dwh-1  Recreate                                                                                 0.0s
 ⠋ Container airbyte-cron                  Creating                                                                                 0.0s
 ⠋ Container airbyte-server                Creating                                                                                 0.0s
 ⠋ Container airbyte-worker                Creating                                                                                 0.0s
Error response from daemon: invalid mount config for type "bind": bind source path does not exist: /host_mnt/Users/kas772/Surendra/os-data-stack/flags.yml

**Comment by surenganne** [comment]
flags.yml is missing in your repo

**Comment by alonsomedo** [comment]
Could you give me more detail? I have deployed everything again without issues on windows

**Comment by surenganne** [comment]
I am sure. do you see flags.yml in your repo?

**Comment by alonsomedo** [comment]
ohh yes there is a folder called flags.yml, but in windows it doesn't trigger any error when deploying. I haven't test my code in Mac Os

**Comment by surenganne** [comment]
I am sure. This should also support Linux envs

**Comment by surenganne** [comment]
Requesting you to update your repo accordingly

**Comment by alonsomedo** [comment]
I have deployed on MAC M1 without issues, could you try creating the "flags.yml" FOLDER (not file) before you run docker compose up --build

**Comment by surenganne** [comment]
It's working. Please update your repo accordingly.  I have tried it on my Mac M2.

**Comment by surenganne** [comment]
After added flag.yml as a folder in that repo, It worked.

**Comment by alonsomedo** [comment]
flag.yml file added as a file, it's also working as a file.  Thanks for your feedback
