### ISSUE TITLE
dbt Complex Models DAG

### ISSUE THREAD

**Issue by naveenkumarvadlamudi** [alonsomedo/os-data-stack#4]
Hello @alonsomedo ,

As of now, the code is running the DAGS in the form of a bash operator. This works fine, when the models are small fine but, as the models complexity increases, the orchestrator must do the heavy lifting. So instead of using bash operator, using astronomer or a dbt library that renders dbt models DAGS would a great option.

I knew this is a limitation, not an issue.

Regards,
Naveen

**Comment by alonsomedo** [comment]
Thanks , yeah I known about astronomer provider for DBT , I'll take a look to them more in detail. Which dbt library could you recommend me?

**Comment by naveenkumarvadlamudi** [comment]
Hi @alonsomedo 

This was the one that i was talking about, consider this option,

https://pypi.org/project/astronomer-cosmos/

It renders dbt workflow as a separate dag instead of ruining everything in a single bash operator.

Regards,
Naveen

**Comment by alonsomedo** [comment]
Thanks I'll be testing that library to update my dag

**Comment by alonsomedo** [comment]
Thanks dag using cosmos library was added.

Reference PR:

https://github.com/alonsomedo/os-data-stack/pull/12
