### ISSUE TITLE
Airbyte is continuously restarting and unable to access

### ISSUE THREAD

**Issue by surenganne** [alonsomedo/os-data-stack#6]
Airbyte is continuously restarting and unable to access

cd1d6c84be2b   airbyte/server:0.44.3                                  "/bin/bash -c ${APPL…"   27 minutes ago   Restarting (1) 37 seconds ago                                                                                                                      airbyte-server

**Comment by surenganne** [comment]
Rest other services are working as expected.

**Comment by alonsomedo** [comment]
are you using Windows 10?

**Comment by alonsomedo** [comment]
If you are having problems with airbyte-webapp and airbyte-proxy on windows , please run the below commands in order:

1. Clone the latest version of the project.
2. `net stop winnat`
3. `docker compose up --build`
4. `net start winnat`

**You just need to run the above commands one time, next time you run `docker compose ...` you shouldn't have any problem.**

Sometimes windows restric some ports that the containers are using, to validate which ports are getting restricted you can run the below command:

`netsh int ipv4 show excludedportrange protocol=tcp`
